# Generated by Django 5.2.6 on 2026-07-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["-score", "-waves_cleared", "-enemies_destroyed", "created_at"],
                name="leaderboard_rank_idx",
            ),
        ),
    ]
