# Generated by Django 5.2.6 on 2026-07-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_leaderboardentry_leaderboard_rank_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="abilities_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="difficulty",
            field=models.CharField(blank=True, default="normal", max_length=30),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="game_seed",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="scenario",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="towers_built",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="towers_upgraded",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
